### ISSUE TITLE
When a player not included in the whitelist tries to log in, a logout log appears

### ISSUE THREAD

**Issue by lolplay123** [NewAmazingPVP/ProxyPlayerNotify#2]
I am currently using this plugin along with the velocity-whitelist plugin on a Velocity server. Every time a player not included in the whitelist tries to log in to the server, two logout logs appear. How can I prevent logout logs from appearing when a player not included in the whitelist attempts to log in?

**Comment by NewAmazingPVP** [comment]
Interesting @lolplay123 Try using [this version](https://cdn.discordapp.com/attachments/1103464645899079743/1232126359401136248/ProxyPlayerNotify-potentialFix.jar?ex=66285297&is=66270117&hm=bc5dd3bee6a933f3152e2c3568545103d03884918e6abae1dce5d07fb1a61a96&) where I have changed the trigger event and let me know if that fixes it. It was posted on Discord, but it's a beta version, so if it works, I'll publish it.

**Comment by lolplay123** [comment]
Thank you for creating the test plugin so quickly. When I tried it, both login and logout logs were displayed.

P.S. Btw, I am using the following whitelist plugin
https://github.com/BBaoVanC/bobawhitelist

**Comment by lolplay123** [comment]
Also, a bug was found in the test version. Your own login log is not displayed when you log in.

**Comment by NewAmazingPVP** [comment]
@lolplay123 Thank you for sending me the plugin you are using. I have tweaked the event triggers to account for the sequence and to reduce false triggers. Let me know if [this new beta version](https://cdn.discordapp.com/attachments/1103464645899079743/1232429674680946799/ProxyPlayerNotify-bugfixBeta.jar?ex=66296d13&is=66281b93&hm=c7473aa8182b411b7c15efbf9e31c08fed696d6c83805fae4ccd5172beb3211c&) works as intended or not.

**Comment by NewAmazingPVP** [comment]
Just released a new version https://www.spigotmc.org/resources/proxyplayernotify.108035/download?version=538452

**Comment by lolplay123** [comment]
I was impressed! This new release is working as intended. Thank you for responding so sincerely.

**Comment by NewAmazingPVP** [comment]
Perfect, glad I could help you!
