### ISSUE TITLE
Players without ppn.view permission still see others' join/switch/leave messages

### ISSUE THREAD

**Issue by Ben569483** [NewAmazingPVP/ProxyPlayerNotify#7]
I'm trying to set up ProxyPlayerNotify in a way where staff members can see when other staff members join or leave the network or switch server. The problem is that players without the ppn.view permission can still see staff join/switch/leave messages. I'm using a Velocity proxy with LuckPerms-Velocity 5.4.139. I have permissions, notify_message and hide_message all set to true in the config. I'm not sure if it's a bug or if I'm doing something stupid. I've tried specifically setting the permissions to "false" for non-staff groups but still the same result.
![image_2024-08-19_224644650](https://github.com/user-attachments/assets/54c2dbd0-72cc-485f-b968-9392e18c71ba)

**Comment by NewAmazingPVP** [comment]
@Ben569483  How does your luckperms group permisions look right now? Based on what you are trying to achieve, I would order the perms like this.

The staff group would get ppn.notify and ppn.view perms.

The default group would get no perms at all (remove any perms with related to ppn; don't set it to false either, I know it's weird, but this was my first time interacting with luckperms, so having it set to false might be interfering, so just remove it completely and see if that works).

**Comment by Ben569483** [comment]
This is where the PPN permissions are on my proxy. I've removed all PPN perms outside of staff groups but still persists. These staff groups are the only place where the permission is listed, I haven't given it to any users individually.

![image_2024-08-20_004353694](https://github.com/user-attachments/assets/d459947e-2815-4bd3-b347-47472eb9061d)

**Comment by NewAmazingPVP** [comment]
@Ben569483 There was indeed a bug in the code. Please try this [build](https://cdn.discordapp.com/attachments/1103725182314614834/1275520155040088088/ProxyPlayerNotify-permissionsFix.jar?ex=66c63036&is=66c4deb6&hm=06b9e05f9f1d46edb0b3edbf9ecb6e1a10c585522f5ab8e6c5c0040c3b5d3ee6&) out and let me know if it works as intended. Thanks for pointing out the bug!

**Comment by Ben569483** [comment]
Looks like it works as it should do now. Thanks!

**Comment by NewAmazingPVP** [comment]
Amazing! Thank you again for reporting the bug, and please feel free to open this again if something happens.
